# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/bibekkhakural80-ui/Encryption-Decryption-System/blob/main/Untitled1.ipynb

Hello world
"""

"""
Assignment: File Encryption and Decryption System
Author: Bibek Khakural and Bibek Pantha

Description:
This program:
1. Reads text from 'raw_text.txt'
2. Encrypts it using custom rules
3. Saves to 'encrypted_text.txt'
4. Decrypts it back to 'decrypted_text.txt'
5. Verifies correctness


"""

# -------------------------------
# Step 1: Create raw file
# -------------------------------

def create_raw_file():
    with open("raw_text.txt", "w") as f:
        f.write("""Hello World!
This is my encryption test.
abc xyz ABC XYZ""")
    print("raw_text.txt created")


# -------------------------------
# Encryption
# -------------------------------

def encrypt_file(shift1, shift2):
    with open("raw_text.txt", "r") as infile, open("encrypted_text.txt", "w") as outfile:
        text = infile.read()
        result = ""

        for ch in text:
            if ch.islower():
                pos = ord(ch) - ord('a')

                if pos <= 12:  # a-m
                    new_pos = (pos + shift1 * shift2) % 26
                    result += chr(new_pos + ord('a')) + "1"   # mark rule 1
                else:  # n-z
                    new_pos = (pos - (shift1 + shift2)) % 26
                    result += chr(new_pos + ord('a')) + "2"   # mark rule 2

            elif ch.isupper():
                pos = ord(ch) - ord('A')

                if pos <= 12:
                    new_pos = (pos - shift1) % 26
                    result += chr(new_pos + ord('A')) + "3"
                else:
                    new_pos = (pos + shift2**2) % 26
                    result += chr(new_pos + ord('A')) + "4"

            else:
                result += ch

        outfile.write(result)

    print("Encryption completed")


# -------------------------------
# Decryption (PERFECT)
# -------------------------------

def decrypt_file(shift1, shift2):
    with open("encrypted_text.txt", "r") as infile, open("decrypted_text.txt", "w") as outfile:
        text = infile.read()
        result = ""

        i = 0
        while i < len(text):
            ch = text[i]

            if ch.isalpha():
                rule = text[i+1]  # read marker
                i += 2

                if ch.islower():
                    pos = ord(ch) - ord('a')

                    if rule == "1":
                        new_pos = (pos - shift1 * shift2) % 26
                    else:
                        new_pos = (pos + (shift1 + shift2)) % 26

                    result += chr(new_pos + ord('a'))

                elif ch.isupper():
                    pos = ord(ch) - ord('A')

                    if rule == "3":
                        new_pos = (pos + shift1) % 26
                    else:
                        new_pos = (pos - shift2**2) % 26

                    result += chr(new_pos + ord('A'))

            else:
                result += ch
                i += 1

        outfile.write(result)

    print("Decryption completed")


# -------------------------------
# Verification
# -------------------------------

def verify_files():
    with open("raw_text.txt", "r") as f1, open("decrypted_text.txt", "r") as f2:
        if f1.read() == f2.read():
            print("SUCCESS: Decryption matches original!")
        else:
            print("FAILURE: Decryption does NOT match")


# -------------------------------
# Display
# -------------------------------

def show_files():
    print("\n--- RAW TEXT ---")
    print(open("raw_text.txt").read())

    print("\n--- ENCRYPTED TEXT ---")
    print(open("encrypted_text.txt").read())

    print("\n--- DECRYPTED TEXT ---")
    print(open("decrypted_text.txt").read())


# -------------------------------
# Main
# -------------------------------

def main():
    print(" = Encryption/Decryption System =")

    create_raw_file()

    shift1 = int(input("Enter shift1: "))
    shift2 = int(input("Enter shift2: "))

    encrypt_file(shift1, shift2)
    decrypt_file(shift1, shift2)
    verify_files()
    show_files()


main()
